name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "acrinfofd22210.azurecr.io" # Nom du registy
  IMAGE_NAME: "info210-retro-nolhan" # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login
        run: | # le echo, | et stdin c'est pour ne pas afficher le mdp dans les logs 
          echo "${{ secrets.PASSWORD }}" | docker login ${{ env.REG_NAME }} -u ${{ secrets.USERNAME }} --password-stdin
      - name: build
        run: |
          docker build -t ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ./api/

  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: 'https://todo.nolhanvandenbroe.emf-informatique.ch/'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          configPath: '.lighthouserc.json'
